version: "3.1"
services:
  gateway:
    image: sashman/birin_gateway:latest
    env_file: .env
    ports:
      - 4001:4001
    deploy:
      restart_policy:
        condition: any
  api:
    image: sashman/birin_api:latest
    environment:
      DATABASE_URL: $DATABASE_URL
    ports:
      - 4000:4000
    deploy:
      restart_policy:
        condition: any
