version: "3.1"
services:
  gateway:
    image: sashman/birin_gateway:latest
    ports:
      - 4001:4001
    environment:
      API_ENDPOINT: http://api:4000
    depends_on:
      - api
    deploy:
      restart_policy:
        condition: any
  api:
    image: sashman/birin_api:latest
    environment:
      DATABASE_URL: $DATABASE_URL
    ports:
      - 4000:4000
    deploy:
      restart_policy:
        condition: any
